import type { Metadata } from "next";
import "./globals.css";
import Cabecalho from "@/components/Cabecalho/page";
import Rodape from "@/components/Rodape/page";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="pt-br">
            <body>
                <Cabecalho />
                <div className="container min-h-[60vh]">
                    {children}
                </div>
                <Rodape />
            </body>
        </html>
    );
}
